/*
 * This source file was generated by the Gradle 'init' task
 */
package lld.parkinglot;

import lld.parkinglot.entities.Ticket;
import lld.parkinglot.entities.Vehicle;
import lld.parkinglot.enums.VehicleType;
import lld.parkinglot.parking.*;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        TwoWheelerParkingSpot spot1 = new TwoWheelerParkingSpot(20, 1);
        TwoWheelerParkingSpot spot2 = new TwoWheelerParkingSpot(20, 2);

        FourWheelerParkingSpot spot3 = new FourWheelerParkingSpot(50, 1);
        FourWheelerParkingSpot spot4 = new FourWheelerParkingSpot(50, 2);

        ParkingSpotManager spotManager = new ParkingSpotManager(Arrays.asList(spot1, spot2, spot3, spot4));

        spotManager.displayAvailability();

        Vehicle vehicle1 = new Vehicle("DL91 ABC", VehicleType.TWO_WHEELER);
        Ticket ticket1 = spotManager.findAndBookParkingSpot(vehicle1);

        spotManager.displayAvailability();

        Vehicle vehicle2 = new Vehicle("KA10 XYZ", VehicleType.FOUR_WHEELER);
        Vehicle vehicle3 = new Vehicle("DL91 QWE", VehicleType.TWO_WHEELER);

        Ticket ticket2 = spotManager.findAndBookParkingSpot(vehicle2);
        Ticket ticket3 = spotManager.findAndBookParkingSpot(vehicle3);

        spotManager.displayAvailability();

        Vehicle vehicle4 = new Vehicle("DL91 QQQ", VehicleType.TWO_WHEELER);
        Ticket ticket4 = spotManager.findAndBookParkingSpot(vehicle4);

        spotManager.displayAvailability();

        spotManager.unparkVehicle(ticket1);
        spotManager.displayAvailability();

    }
}
